language: ruby
cache: bundler
rvm: 2.1
services:
- redis-server
before_script:
- cp config/database.yml.postgres config/database.yml
- cp config/justask.yml.example config/justask.yml
- bundle exec rake db:drop db:create db:migrate db:test:prepare
notifications:
  slack:
    secure: "p+LieMEgRpQQimqT6+Up4cHpbFSyFWoEAzt3gl1yg+cECT2btJR0xkL10Z74gRhNcmcyrhP3IU10u+/RVclqvKAx39bG6r/+8kbyhCA1yXAJRScHwJMKRUqFwT8FV7UWZNyHEbpJmuC2M+VwGAf6PYZcNbfcjZzR8xPdM6+Mjq6mxNTMiJuGCTaL/+FPUOmiTTjl0ZNQqsbyScAtTWh8EMCUIrJ6fif2tESVY1g2DuknOhRAqs6SnhGXmOE+tmmi2bwx8dGULMbFKO9seeqGqHgRO/SJ7+o+qaPXC5pZmdl7gIjLubEQI8pZnLyYnm4mT7LE+LQzuhreHUiEOIvJ43Gxnpq9Dt48spQNIh3oViyw2JVbYE+RprFjfw6Dk1EtgfZ7qQEbUZwkguXZ98kz9ps6w/m3/fKWTOEHheHcCeuN35MnLkZfdUiodTsQuOnwSpMGsIWnOQP0XwiZ7bMshRET/Mg2amZhp6xcIt52ZZbC/ojDRoq+bakmjKWnq5mkZK5EqzTaHm9xo//nMNA0UIPYJyotgmauGc5xkSUHbyy/uf5xMRmcwuiss+VBCMI8z5a1uHkLGd805JU6Gr3OXp8fuiu8zWr80k4+w7vojsS84vvd2ntVktJswXRVrj/e1TdxrYCNY/32bKu23E24ygxtKt//fx0Jif0sCdSHXf4="